# docker-compose.yml
version: '2'
services:

  eh-server-api:
    image: eventhopper-api
    ports: 
        - 8080:8080
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
    - .env

  aggregator-service:
    image: aggregator-service
    ports: 
        - 5005:5005
    build: 
        context: .
        dockerfile: ./src/services/aggregator/Dockerfile
    env_file:
        - .env