# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        TEST_PORT: 1025
        UPDATE_PORT: 1026
        TEST_AUTH_API_KEY: ${{ secrets.SERVER_API_KEY }}
        REALM_APP_ID: ${{ secrets.REALM_APP_ID }}
        TICKETMASTER_CONSUMER_KEY: ${{ secrets.TICKETMASTER }}
        TICKETLEAP_API_KEY: ${{ secrets.TICKETLEAP }}
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        GOOGLE_GEOCODING_API_KEY: ${{ secrets.GEOCODING }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          milliseconds: 1000
