# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ beta ]
  pull_request:
    branches: [ beta, master ]

jobs:
  build:
    env:
        TEST_PORT: 1025
        UPDATE_PORT: 1026
        TEST_AUTH_API_KEY: ${{ secrets.SERVER_API_KEY }}
        REALM_APP_ID: ${{ secrets.REALM_APP_ID }}
        TICKETMASTER_CONSUMER_KEY: ${{ secrets.TICKETMASTER }}
        TICKETLEAP_API_KEY: ${{ secrets.TICKETLEAP }}
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        GOOGLE_GEOCODING_API_KEY: ${{ secrets.GEOCODING }}
        REALM_PUBLIC_KEY: ${{ secrets.REALM_PUBLIC_KEY }}
        REALM_PRIVATE_KEY: ${{ secrets.REALM_PRIVATE_KEY }}
        MONGO_PROJECT_ID: ${{ secrets.MONGO_PROJECT_ID }}
        REALM_NUMERICAL_APP_ID: ${{ secrets.REALM_NUMERICAL_APP_ID }}
        FSAV_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FSAV_AUTH_PROVIDER_X509_CERT_URL }}
        FSAV_AUTH_URI: ${{ secrets.FSAV_AUTH_URI }}
        FSAV_CLIENT_EMAIL: ${{ secrets.FSAV_CLIENT_EMAIL }}
        FSAV_CLIENT_ID: ${{ secrets.FSAV_CLIENT_ID }}
        FSAV_CLIENT_X509_CERT_URL: ${{ secrets.FSAV_CLIENT_X509_CERT_URL }}
        FSAV_PRIVATE_KEY: ${{ secrets.FSAV_PRIVATE_KEY }}
        FSAV_PRIVATE_KEY_ID: ${{ secrets.FSAV_PRIVATE_KEY_ID }}
        FSAV_PROJECT_ID: ${{ secrets.FSAV_PROJECT_ID }}
        FSAV_TOKEN_URI: ${{ secrets.FSAV_TOKEN_URI }}
        FSAV_TYPE: ${{ secrets.FSAV_TYPE }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:users
    - run: npm run test:server
    - run: npm run test:events
